### ISSUE TITLE
Grafana not loading

### ISSUE THREAD

**Issue by Tuumke** [philhawthorne/docker-influxdb-grafana#1]
Have setup the docker following the instructions. I created 2 shares on /volume1 of my Synology in the same way. Both with the same permissions.
/volume1/InfluxDB is being written to, /volume1/Grafana isnt.
Even when i change it to /volume1/InfluxDB/grafana, influx is writing data, Grafana isnt.

t=2017-12-06T14:50:32+0000 lvl=info msg="Starting Grafana" logger=main version=4.1.1 commit=v4.1.1 compiled=2017-01-12T08:48:03+0000
t=2017-12-06T14:50:32+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-12-06T14:50:32+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-12-06T14:50:32+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-12-06T14:50:32+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-12-06T14:50:32+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-12-06T14:50:32+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_DATABASE_TYPE=sqlite3"
t=2017-12-06T14:50:32+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-12-06T14:50:32+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-12-06T14:50:32+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-12-06T14:50:32+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2017-12-06T14:50:32+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-12-06T14:50:32+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-12-06T14:50:32+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: unable to open database file\n"

**Comment by Tuumke** [comment]
Just tried an install on a W10 machine with fresh docker.
Could map to c:\docker\grafana and \influxdb. 
Running from start. I wonder why on Synology this isnt working.

**Comment by Tuumke** [comment]
Using a different directory (/volume1/docker/grafana) did the trick. Now it seems to be running fine..
docker run -d --name grafana -p 3003:3003 -p 3004:8083 -p 8086:8086 -p 22022:22 -v /volume1/InfluxDB:/var/lib/influxdb -v /volume1/docker/grafana:/var/lib/grafana philhawthorne/docker-influxdb-grafana:latest

**Comment by philhawthorne** [comment]
Glad you got it sorted. Out of curiosity what was the original filepath you were mounting to?

I'm wondering if Synology have the internal system filepaths locked down, as they will be on internal memory.

**Comment by Tuumke** [comment]
Originally i had it setup as below
-v /volume1/InfluxDB:/var/lib/influxdb
-v /volume1/Grafana:/var/lib/grafana
The InfluxDB was working, but the Grafana wasnt.
So now its set to 
-v /volume1/InfluxDB:/var/lib/influxdb
-v /volume1/docker/grafana:/var/lib/grafana

**Comment by philhawthorne** [comment]
Strange that it didn't like the Grafana folder. I wonder if it already existed and there was a permission issue or something. Not sure. At least changing into another subfolder got it working for you

**Comment by sloansony** [comment]
I've had the same problem. Thanks for the solution.

**Comment by RiriReset** [comment]
I've had the same problem too.
Indeed, it seems to be a problem of access rights to /var/lib/grafana
I fixed it this way -> 
run bash under the container
just give all access with "chmod 0755 /var/lib/grafana"
Fixed the problem for me.
(Same thing could happen with /var/lib/influxdb so apply the same chmod)
