### ISSUE TITLE
how is the influxdb database kept?

### ISSUE THREAD

**Issue by tessus** [philhawthorne/docker-influxdb-grafana#14]
Hi Phil,

I would have rather sent an email, but couldn't find one anywhere. Not on your homepage, not on your gh profile, ...

I'm wondering how the database is not deleted when destroying the container. I was playing around with the official influxdb image which I have deployed via kubernetes. However, every time I delete the pod, the db gets wiped out.
Is it just a matter of setting `-v /path/for/grafana:/var/lib/grafana` or did you do something special in your image?

Unfortunately we have a requirement to separate grafana and influxdb in separate environments, thus I cannot use your image. But it is a great approach and I would use it in a heartbeat, if I was allowed to...

**Comment by philhawthorne** [comment]
Hey @tessus 

The setup instructions for this image have `-v /path/for/influxdb:/var/lib/influxdb` , which allows you to persist the data stored in InfluxDB to your local filesystem. 

You should be able to do something similar with the official Influx container. You'll just need to find out where in the container the data is stored, and then map it to a volume on your host.

Cheers!

**Comment by tessus** [comment]
Thanks for your reply and the info.
