### ISSUE TITLE
Persist changes in grafana and influxdb

### ISSUE THREAD

**Issue by njss** [philhawthorne/docker-influxdb-grafana#15]
Hi, silly question.
But how do I persist my changes to Grafana and InfluxDB.
Every time I restart everything is lost...

Thanks in advance

**Comment by philhawthorne** [comment]
Hmm sounds like your container can't write to the file system.

In your `docker run` command you should have specified the file paths

```bash
-v /path/for/influxdb:/var/lib/influxdb \
-v /path/for/grafana:/var/lib/grafana \
```

Just make sure that on your host, those directories exist and are writable. You may need to give them `0777` permissions to allow other systems (ie the docker container) to write into that directory.

**Comment by njss** [comment]
Thanks, it works now!
