### ISSUE TITLE
Typo in docker Hub Documentation

### ISSUE THREAD

**Issue by ufulu** [philhawthorne/docker-influxdb-grafana#16]
Hi Phil, 

great fan, love your blog posts. Just a minor issue I stumbled upon when coming from https://hub.docker.com/r/philhawthorne/docker-influxdb-grafana/ I had a hard time getting the docker up and running. It seems there is a typo in the documentation on docker hub: instead of `-p 3004:8888 \` it should be `-p 3004:8083 \` like in the Readme here on github. 

Cheers, really appreciate your work and looking forward to your next automation post! :)

**Comment by philhawthorne** [comment]
Thanks @ufulu 

Ugh, how annoying. I've fixed that now. Thanks for the heads up!

Cheers
