### ISSUE TITLE
port settings

### ISSUE THREAD

**Issue by Mariusthvdb** [philhawthorne/docker-influxdb-grafana#2]
hi Phil,
thanks for your pages, finally im almost getting there....

following your setup guide I've managed to run influxdb and grafana like this:

```
docker run -d \
  --name docker-influxdb-grafana \
  -p 3003:3003 \
  -p 3004:8083 \
  -p 8086:8086 \
  -p 22022:22 \
  -v /volume1/docker/InfluxDB:/var/lib/influxdb \
  -v /volume1/docker/Grafana:/var/lib/grafana \
  --restart=always \
  philhawthorne/docker-influxdb-grafana:latest
```

since i am running HomeAssistant on a Pi3 and not locally on the Synology, i cant use localhost, but have it pointed to my nas on <ipaddress>.

In HomeAssistant configuration.yaml I've added

influxdb:
  host: ipaddress
  port: 3004

but then error log shows:

```
2018-01-25 15:15:34 ERROR (MainThread) [homeassistant.setup] Error during setup of component influxdb
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 371, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3.6/site-packages/urllib3/util/url.py", line 199, in parse_url
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: ipaddress:3004:8086
```

It seems the default port 8086  is added after whichever host is written? 

What port should i change best for the influxdb to start running correctly? Leaving the port 3004 out doesn't work either, it won't see Influxdb at all then

`2018-01-25 16:54:09 ERROR (SyncWorker_12) [homeassistant.components.influxdb] Database host is not accessible due to '', please check your entries in the configuration file (host, port, etc.) and verify that the database exists and is READ/WRITE.`

btw, since inluxdb and grafana are running on my password protected NAS, do we need to enter those credentials in the setup/config too? 'Homeassistant' being a user on the Synology  and changing rights to read/write on the docker would not suffice?

Hope you can have a quick look,
thanks!
Marius

**Comment by philhawthorne** [comment]
Hey Marius.

Sorry for taking so long to reply. Did you ever get this solved? Seems like a strange error Home Assistant was throwing.
