### ISSUE TITLE
InfluxDB Failing to load on start

### ISSUE THREAD

**Issue by philhawthorne** [philhawthorne/docker-influxdb-grafana#26]
Here is what I see:

I can get into Grafana, but influxdb is failing.

root@653cddbb36d5:/var/log/grafana# tail -f /var/log/grafana/grafana.log
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing ServerLockService" logger=server
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing TracingService" logger=server
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing UsageStatsService" logger=server
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing UserAuthTokenService" logger=server
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing CleanUpService" logger=server
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing NotificationService" logger=server
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing provisioningServiceImpl" logger=server
t=2019-08-20T21:28:12+0000 lvl=info msg="Initializing Stream Manager"
t=2019-08-20T21:28:12+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3003 protocol=http subUrl= socket=
t=2019-08-20T21:31:30+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=root method=GET path=/api/datasources/proxy/1/query status=502 remote_addr=192.168.1.52 time_ms=0 size=0 referer="http://192.168.1.52:3003/?orgId=1"

_Originally posted by @moore66982 in https://github.com/philhawthorne/docker-influxdb-grafana/issues/24#issuecomment-523204061_

**Comment by philhawthorne** [comment]
Hi @moore66982 

I don't see these errors on my side, and Influx is able to boot for me.

Do you mind aletering your `docker run` slightly to point to a new directory for InfluxDB? I'm wondering if your existing InfluxDB is somehow corrupt and won't load. 

(By using a new directory, we won't lose any data in your existing Influx database)

**Comment by RaychelM** [comment]
Hi @philhawthorne ,

Don't know if this is related, but since yesterday I'm trying to get you docker container to run but having trouble with influxdb.
After checking the supervisor log I found the following:

/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
influxdb-stdout---supervisor-ErEZMW.log (END)

I've installed and running the container thru the Synology Docker interface.

Any tips on resolving this?

Thanks

**Comment by philhawthorne** [comment]
Thanks @RaychelM 

I am not sure why that error came up. I can see where in the code that error is being raised, but not sure why.

I've made some adjustments to the `edge` tag which will _hopefully_ solve this for you. Can you try and let me know how you go?

**Comment by RaychelM** [comment]
Hi @philhawthorne 

Just tried the edge tag, but still getting the error.

root@docker-influxdb-grafana:/var/log/supervisor# cat influxdb-stdout---supervisor-C41pz2.log
/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
/var/run/influxdb/influxd.pid not writable, check permissions [ FAILED ]
root@docker-influxdb-grafana:/var/log/supervisor#

**Comment by philhawthorne** [comment]
Thanks for trying @RaychelM 

Are you able to try running the container via `docker run` in the terminal? I am wondering if the Synology UI is making the container have higher restrictions than normal.

If you're on DSM 6 you'll just need to prefix your `docker run` with `sudo`

**Comment by RaychelM** [comment]
Thanks for your time and help @philhawthorne 

Just like you suggested, tried running the container in a terminal and it works...
Lesson learned, UI isn't always best or easier!

Thanks again...
