### ISSUE TITLE
Influxdb won't start.

### ISSUE THREAD

**Issue by markrennie71** [philhawthorne/docker-influxdb-grafana#3]
Hi Phil

I've been using this for sometime now with no problems at all. I did a reboot on my system today and all my dockers came back fine, including this one, but for some reason influxdb hasn't started, Grafana has. Is there anything I can do to kick start it please?

Cheers
Mark

**Comment by philhawthorne** [comment]
Hey Mark,

Interesting. If no amount of `docker restart` will help, then you can SSH in on port `22022` with username and password both as root. 

Once inside the container, you can issue a `/etc/init.d/influxdb start` to start InfluxDB manually

**Comment by markrennie71** [comment]
thanks Phil.. 10 restarts and it started. Most odd! I will keep that command up my sleeve for next time. Cheers
