### ISSUE TITLE
Imported data shows wrong timestamp

### ISSUE THREAD

**Issue by Loader23** [philhawthorne/docker-influxdb-grafana#37]
Hi,

iam currently trying to import old values from home-assistant but the timestamp is not working correctly.

This Timestamp 1588221453 should be 2020-04-30   06:37:33.004826
The date is correct in Influx but the time 6:12. 

I have imported via API to use seconds as precision but its the same whith nanosecond converted timestamps. 
Adding entrys without timestamps gives the current correct time.

Any Ideas?

**Comment by zerog2k** [comment]
@Loader23 
can you provide an exact example write and read from api which is able to reproduce this, e.g.
curl POST write and query examples?


using slightly modified examples from:
https://docs.influxdata.com/influxdb/v1.8/guides/write_data/
https://docs.influxdata.com/influxdb/v1.8/guides/query_data/

```
# create db
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

# insert datapoint, specifying seconds precision
curl -i -XPOST 'http://localhost:8086/write?db=mydb&precision=s' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1588221453'

# query data
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=SELECT \"value\" FROM \"cpu_load_short\" WHERE \"region\"='us-west'"

{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "cpu_load_short",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2020-04-30T04:37:33Z",
                            0.64
                        ]
                    ]
                }
            ]
        }
    ]
}
```
```
# timestamp looks correct
$ date -u -d @1588221453
Thu Apr 30 04:37:33 UTC 2020
```

**Comment by Loader23** [comment]
I have the same results as you:
```
`{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "cpu_load_short",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2020-04-30T04:37:33Z",
                            0.64
                        ]
                    ]
                }
            ]
        }
    ]
}
```
But in Chronograf I got 30.04. 6:00
How does your Chronograf look like?

**Comment by zerog2k** [comment]
sorry, im only using influxdb+grafana ;)

are you sure what you are seeing isn't some product of time aggregation/rollup?
also, what about display timezone?

for example, if I look at this in grafana, i can see that looking over past 30 days, the default $time_interval seems to be rolling up to 30 minutes
![Screen Shot 2020-05-27 at 9 02 57 AM](https://user-images.githubusercontent.com/3943170/83030813-6fd31900-9ff9-11ea-98b0-851897794eb7.png)

but if zoom in i can see it looks better (1m):
![Screen Shot 2020-05-27 at 9 03 37 AM](https://user-images.githubusercontent.com/3943170/83030841-7792bd80-9ff9-11ea-9375-68664fd12718.png)

and finally to the 1s interval:
![Screen Shot 2020-05-27 at 9 03 55 AM](https://user-images.githubusercontent.com/3943170/83030865-7e213500-9ff9-11ea-8e7c-f736fecad8cc.png)

note that also my display TZ (UTC-0500) is coming into play here

**Comment by Loader23** [comment]
There does not seem to be a rollup in Chronograf but it explains why I also had these times in Grafana. 
I then only tested in Chronograf and always saw the wrong times but it really seems to be a visual bug.
The dates are correct in the DB and are correct in Grafana. I can live with that :-)

So thanks alot for your time and the solution 👍
