### ISSUE TITLE
upgrade?

### ISSUE THREAD

**Issue by asantaga** [philhawthorne/docker-influxdb-grafana#4]
Hi Phil nice docker image, just wondering if you were planning to update it to the latest grafana/influxdb???

**Comment by philhawthorne** [comment]
Thanks! Can't ake all the credit for it though.

Yes, eventually I'd like to have these upgraded to the latest versions. Not sure when though

**Comment by humbertodias** [comment]
Hi. Try with this PR https://github.com/philhawthorne/docker-influxdb-grafana/pull/5

**Comment by diogopms** [comment]
Can we close this issue? @philhawthorne

**Comment by philhawthorne** [comment]
@diogopms I'll close this once the `dev` branch is merged to master 👍

**Comment by philhawthorne** [comment]
FIxed in #23
