### ISSUE TITLE
Grafana doesn't load in iFrames

### ISSUE THREAD

**Issue by philhawthorne** [philhawthorne/docker-influxdb-grafana#41]
@philhawthorne thanks have been rebuilding my docker containers for the last day and have found several issues I didn't had before. One of the, is while I'm trying to have grafana loaded embed with HA in a iframe, noticed I need to change the grafana.ini to allow that. Didn't managed to do ssh to the localhost as it was giving me several errors, managed to achieve that searching for the file using the command find . -name "grafana.ini" and then just edit via vi command, it worked for em :)

root@pauloserver:/volume2/@docker/aufs/diff/3ef8f4769cc95373371b06b595946674dde27939eb9500d9c9e8cef363e6f1a8/etc/grafana# vi grafana.ini

_Originally posted by @paazevedo in https://github.com/philhawthorne/docker-influxdb-grafana/issues/7#issuecomment-674393257_

**Comment by philhawthorne** [comment]
@paazevedo I've pushed an update to the `edge` tag that should solve this.

Are you able to run `philhawthorne/docker-influxdb-grafana:edge` and let me know if you can login and use from within a Home Assistant panel now?

If you're running it via SSL, you might need to still update the grafana.ini file to enable SSL cookies

**Comment by paazevedo** [comment]
@philhawthorne thank you sir :) it's working now across all platforms :)
