### ISSUE TITLE
Update Grafana to latest version (7.2)

### ISSUE THREAD

**Issue by oester** [philhawthorne/docker-influxdb-grafana#42]
Can you update to Grafana 7.2? You can tag it with a new version if needed.

**Comment by philhawthorne** [comment]
Sure 

I'll see if I can have that done over the weekend

**Comment by oester** [comment]
I forked your repository and updated grafana to 7.2.0, built just fine. I ran into some issues on chrome - login would redirect back to login page even if successful. I ended up removing "cookie_samesite" and "allow_embedding" from the config file (let them go to default), and that fixed my issues. I don't need iframe embedding for my use case. So you may want to investigate what the issue is before updating. Seemed to be OK on 7.1.5.

**Comment by philhawthorne** [comment]
Thanks for the heads up @oester!

 I made some changes on the `edge` tag under 2d2ff7aea674c4ced88b23f6069599c7f4711b9c and 85dc9b6af5ba35b331da87f4158315bedd858256 as there were some issues with both of those.

Will do a similar thing, push up an update to the edge tag first to flush out anything that might break
