### ISSUE TITLE
cookie_samesite breaks setCookie

### ISSUE THREAD

**Issue by sefininio** [philhawthorne/docker-influxdb-grafana#44]
cookie_samesite=none in [grafana.ini](https://github.com/philhawthorne/docker-influxdb-grafana/blob/master/grafana/grafana.ini#L140) breaks login, Set-Cookie header blocked since it lacks secure attribute.

I changed it to be commented out in /etc/grafana/grafana.ini inside the docker container (so it defaults to Lax), and that solved the issue.

**Comment by sefininio** [comment]
@philhawthorne 
I saw a new latest is published, however this is still an open issue.
This broke in a recent commit 85dc9b6af5ba35b331da87f4158315bedd858256 on Aug 17th.

**Comment by philhawthorne** [comment]
Ah thanks @jsBlackBelt 

I've just pushed an update to the `edge` tag. I'll test it with Home Assistant to make sure it works. Strangely the cookie samesite `none` didn't break for me. 

If `Lax` still works for Home Assistant and is fixed for you, I'll do another merge to master.

Cheers

**Comment by sefininio** [comment]
Thanks @philhawthorne ,

Apparently, this is a known issue:
https://community.grafana.com/t/error-logging-in-user-token-not-found/14996
