### ISSUE TITLE
InfluxDB (chronograf) not reachable

### ISSUE THREAD

**Issue by ArthurTimmermans** [philhawthorne/docker-influxdb-grafana#49]
When I install this docker on my Synology NAS. exactly as listed. I can see the Grafana webpage, but I don't see the influxDB webpage. My grafana is running on 192.168.0.30:3003, but if I go to 192.168.0.30:3004 it says the site is not reachable. How can I check what is happening? and what could be a potential reason for this?

**Comment by philhawthorne** [comment]
Strange working ok for me on my Synology.

Can you please provide your `docker run` command?

Looking at the container, there's a few places to check.

First access the containers terminal by using `docker exec -it <<container name>> /bin/bash`

From there, check these locations

* `/var/log/supervisord`
* `/var/log/supervisor/chronograf-stderr---supervisor-<<xxxx>>.log`

**Comment by ArthurTimmermans** [comment]
I followed the video: [YOUTUBE](https://www.youtube.com/watch?v=YtGSOLOg-LA)

So

`sudo docker run -d --name grafana -p 3003:3003 -p 3004:8083 -p 8086:8086 -p 22022:22 -v /volume1/docker/grafana:/var/lib/grafana -v /volume1/docker/influxdb:/var/lib/influxdb --restart=always philhawthorne/docker-influxdb-grafana`

After performing the following commands:
`/var/log/supervisor`
`/var/log/supervisor/chronograf-stderr---supervisor-<<xxxx>>.log`
I get the response 
`root@d48ecce1add0:/var/log/supervisor# cat chronograf-stderr---supervisor-n1bDOi                                                                                                                                                                                                                           .log`
`time="2020-10-18T07:51:36Z" level=info msg="Moving from version 1.8.0"`
`time="2020-10-18T07:51:36Z" level=info msg="Moving to version 1.8.6"`
`time="2020-10-18T07:51:36Z" level=info msg="Successfully created backup/chronogr                                                                                                                                                                                                                                          af-v1.db.1.8.0"`
`time="2020-10-18T07:51:36Z" level=info msg="Serving chronograf at http://[::]:80                                                                                                                                                                                                                                             83" component=server`
`time="2020-10-18T07:51:36Z" level=info msg="Reporting usage stats" component=usa                                                                                                                                                                                                                                             ge freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version                                                                                                                                                                                                                                             ,cluster_id,uptime"`

So If i see correctly it is not starting a webserver at the IP of my NAS? due to `time="2020-10-18T07:51:36Z" level=info msg="Serving chronograf at http://[::]:80                                                                                                                                                                                                                                             83" component=server`?

Maybe also an extra question. Why did you use `-p 22022:22` in your video? what is that port mapping to?

**Comment by philhawthorne** [comment]
Hmm the video probably is out of date now. Might need to do a new one.

`-p 22022:22` was used as the container previously exposed an SSH server on that port. That has been removed now for better security.

The `Serving chronograf at http://[::]:8083` is correct. This is essentially saying open port `8083` on all network interfaces. I also have that in my logs.

From what I can see Chronograf should be up and running in your container.

Can you execute the following from within the `/bin/bash` of the container (as described above)?

```
curl http://127.0.0.1:8083
```

What output does that give you?

**Comment by ArthurTimmermans** [comment]
Looks like it is generating something

`<!DOCTYPE html><html> <head> <meta http-equiv="Content-type" content="text/html; charset=utf-8"> <title>Chronograf</title> <link rel="shortcut icon" href="/favicon.fa749080.ico"> <link rel="stylesheet" href="/src.13dd0be9.css"></head> <body> <div id="react-root" data-basepath=""></div> <script src="/src.1e3b6d12.js"></script> </body> </html>`

**Comment by ArthurTimmermans** [comment]
Sometimes something stupid like rebooting works...
