### ISSUE TITLE
InfluxDB Error: database not found: InfluxDB

### ISSUE THREAD

**Issue by alfureu** [philhawthorne/docker-influxdb-grafana#50]
I log in to localhost:3003, but whenever I try to add a new database default entry (according to the instructions), I get this error: 

```
InfluxDB Error: database not found: InfluxDB
```

Can you please help?

**Comment by philhawthorne** [comment]
Can you please provide your `docker run` command?

**Comment by alfureu** [comment]
The command is as follows:

```
docker run -d --name docker-influx-grafana -p 3003:3003 -p 3004:8083 -p 8086:8086 -v /home/docker/dig/influxdb:/var/lib/influxdb -v /home/docker/dig/grafana:/var/lib/grafana philhawthorne/docker-influxdb-grafana:latest
```

**Comment by philhawthorne** [comment]
From the error, I am guessing you are trying to connect to an InfluxDB database from this screen:

![image](https://user-images.githubusercontent.com/716711/98487786-33c70400-2279-11eb-8542-6d5cf9ebf89b.png)

If so, have you created the `InfluxDB` database in InfluxDB first?

Best to login to Chronograf at localhost:3004 to get a list of what tables exist. You can see those (and create new ones) from the InfluxDB admin page at http://localhost:3004/sources/1/admin-influxdb/databases (once you have setup Chronograf to connect to InfluxDB)

**Comment by alfureu** [comment]
Thanks, that was a kick to the right direction, I got now `Data source is working`. However, when I go to the Chronograph, I see everywhere `To enable this graph you need to configure the system plugin`. Where is this config exactly? Closing...

**Comment by philhawthorne** [comment]
To be honest I haven't setup any Chronograf dashboards or anything like that. I then use Grafana to setup dashboards based on the data in InfluxDB

**Comment by alfureu** [comment]
Thanks @philhawthorne, roger that. Is there any special tool you use to check the database so you know which entries to fill in the the grafana dashboard? I though it would be listed automatically...

**Comment by philhawthorne** [comment]
@DOFfactory not really. I generally just select the source in Grafana and then use the filters as specified.

If you're using Home Assistant, I have a guide which might help: https://philhawthorne.com/getting-started-with-grafana-influxdb-for-home-assistant/

I essentially followed a similar process to get stats out of Influx from Telegraf as well, which was just trial and error until the graphs populated.

**Comment by alfureu** [comment]
Thank you @philhawthorne for sharing this, very helpful. I will need a weekend to sit on this and educate myself 👍
