### ISSUE TITLE
Deploying docker-influxdb-grafana on fargate

### ISSUE THREAD

**Issue by ctippur** [philhawthorne/docker-influxdb-grafana#51]
Hello,

Have you ventured looking at deploying this image on AWS Fargate? Would it be possible ot leverage EFS filesystem for persistance?

Shekar

**Comment by philhawthorne** [comment]
Hi,

Unfortunately not. As the primary purpose I used this for Home Assistant in a local network.

I guess if you can use Docker volume mounts, I can't see why that wouldn't work. But I personally don't have experience with Fargate to know for sure.
