### ISSUE TITLE
Easy way to install plugins? .env

### ISSUE THREAD

**Issue by mspencerl87** [philhawthorne/docker-influxdb-grafana#54]
Is there a way to install plugins? What is the preferred method docker exce -it container /bin/bash 
grafana-cli install xxx?
Or could you do a .env file something like this?
GRAFANA_PLUGINS=grafana-piechart-panel
https://github.com/alekece/tig-stack/blob/master/.env

**Comment by philhawthorne** [comment]
I actually just use the mount folder to unzip the plugins to. This way the plugins are always installed even when I destroy the container etc.

In your `docker run` there is the `-v /path/for/grafana:/var/lib/grafana` flag. Just create a new folder in that directory (on your host) called `plugins`. From there, each plugin you want to install should be in its own folder. For example, here are some of the plugins I have installed

* `/path/for/grafana/plugins/grafana-piechart-panel/`
* `/path/for/grafana/plugins/natel-discrete-panel-0.0.9/`

**Comment by mspencerl87** [comment]
Thank you @philhawthorne
