### ISSUE TITLE
No ports binding

### ISSUE THREAD

**Issue by fewrainbows** [philhawthorne/docker-influxdb-grafana#66]
Hello!

maybe stupid question.
When I launch the latest container, I see no exposed ports.

In the readme I see (and really neeed) at least 3

![immagine](https://github.com/philhawthorne/docker-influxdb-grafana/assets/88545208/294f3a6d-bb8b-4c82-ac64-437527884b72)

Where I'm wrong?

Thanks

**Comment by philhawthorne** [comment]
Hey

Can you please send me the `docker run` command you're using to start this? Or how you're using the container?

**Comment by fewrainbows** [comment]
Sadly by double clicking on the pull container.

Docker desktop for windows.

It's really hard to get to the run docker file in Docker desktop. I'm
beginner user.

Thank you in advance for your help

**Comment by fewrainbows** [comment]
![immagine](https://github.com/philhawthorne/docker-influxdb-grafana/assets/88545208/1fe7c9e0-bd26-4cbf-961a-b03ccd6f23ff)

**Comment by fewrainbows** [comment]
Plain docker run copypaste

docker run --hostname=cc400cede8cb --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=DEBIAN_FRONTEND=noninteractive --env=LANG=C.UTF-8 --env=INFLUXDB_VERSION=1.8.2 --env=CHRONOGRAF_VERSION=1.8.6 --env=GRAFANA_VERSION=7.2.0 --env=GF_DATABASE_TYPE=sqlite3 --volume=C:\Users\Myvol v1:\Myvol --workdir=/root --label='maintainer=Phil Hawthorne <me@philhawthorne.com>' --runtime=runc -d philhawthorne/docker-influxdb-grafana:latest

**Comment by fewrainbows** [comment]
![immagine](https://github.com/philhawthorne/docker-influxdb-grafana/assets/88545208/4a7a78c5-9d17-49f1-be51-9c1b4138148a)

**Comment by philhawthorne** [comment]
Sorry unfortunately I'm not familiar with the Windows Desktop GUI version of Docker.

The dockerfile of this repo doesn't have any `EXPOSE` directives, so guessing thats why it won't show up.

**Comment by fewrainbows** [comment]
Hello,

launched via Powershell....it worked!

`docker run -d \
  --name docker-influxdb-grafana \
  -p 3003:3003 \
  -p 3004:8083 \
  -p 8086:8086 \
  -v /path/for/influxdb:/var/lib/influxdb \
  -v /path/for/grafana:/var/lib/grafana \
  philhawthorne/docker-influxdb-grafana:latest`

Temo fixed from my side

Thanks for you Job!
