### ISSUE TITLE
How to edit grafana.ini

### ISSUE THREAD

**Issue by kaned** [philhawthorne/docker-influxdb-grafana#7]
How can I edit the grafana.ini file to enable anonymous? I have tried adding /var/lib/grafana/grafana.ini and copied over the grafana.ini file from your repo, and then enabled auth.anonymous and bounced the container, but nothing has changed. 

Is my path correct? Am I missing something else? I am pretty new to working with Docker images.

**Comment by twonk** [comment]
You can login to the grafana instance using

`ssh root@YourDockerHost -p 22022`

then edit the grafana.ini using nano:

`nano /etc/grafana/grafana.ini`

save your changes (CTRL+x) then exit the ssh session and restart the grafana container.   
Hopefully you'll be able to see the changes that you made in the Server Admin page under the Settings tab.

**Comment by philhawthorne** [comment]
Hey @kaned 

@twonk is right. You can SSH in using the `22022` port.

Your other option would be to mount the volume in your docker run command, such as `-v $PWD/grafana:/etc/grafana` however you'll need all the files that Grafana needs in there yourself.

**Comment by kaned** [comment]
Perfect! That worked really nice and easy. Thanks!

P.S. @philhawthorne love the podcast! Been listening since the first episode.

**Comment by philhawthorne** [comment]
@kaned awesome! Glad you're enjoying it 😃

**Comment by germansokolov13** [comment]
Worth mention that we could also employ environment variables instead of editing a file:
https://grafana.com/docs/grafana/latest/installation/configuration/#configure-with-environment-variables

**Comment by philhawthorne** [comment]
Good point @germansokolov13

**Comment by paazevedo** [comment]
@philhawthorne thanks have been rebuilding my docker containers for the last day and have found several issues I didn't had before. One of the, is while I'm trying to have grafana loaded embed with HA in a iframe, noticed I need to change the grafana.ini to allow that. Didn't managed to do ssh to the localhost as it was giving me several errors, managed to achieve that searching for the file using the command find . -name "grafana.ini" and then just edit via vi command, it worked for em :)

root@pauloserver:/volume2/@docker/aufs/diff/3ef8f4769cc95373371b06b595946674dde27939eb9500d9c9e8cef363e6f1a8/etc/grafana# vi grafana.ini

**Comment by philhawthorne** [comment]
huh yeah you're right.

Looks like browsers now are starting to be more strict on what pages can be displayed in an iFrame. I just tried my Grafana (turns out I never use the HASS interface to access it) and sure enough, it was blocked. Same for Grocy as well.

**Comment by paazevedo** [comment]
> huh yeah you're right.
> 
> Looks like browsers now are starting to be more strict on what pages can be displayed in an iFrame. I just tried my Grafana (turns out I never use the HASS interface to access it) and sure enough, it was blocked. Same for Grocy as well.

found 2 issues on latest Grafana build, one is the fact by default doesn't allow to load in iframes. You need to go to the config and set allow_embed= true. The second is the continuous redirect within the login page when you load again from an iframe. Here it's related with the cookies that are supposed to hold your session. The only way I managed to solve this was cookie_samesite to none and cookie_secure to true.

Interesting Chrome fails, while Edge (Dev in specific with stable is the same) works fine...still to understand how this works specifically but didn't had time to troubleshoot it, need to take a fiddler trace and check what's going on with the cookies in specific.
